options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step: Clone the repository using GitHub token passed as substitution
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cloning the repository..."
        git config --global credential.helper 'store --file=/root/.git-credentials'
        echo "https://${_GITHUB_PAT}:@github.com/VIGNESYOZY/public_vitejs_staticsite_brainwave.git" > /root/.git-credentials
        git clone https://github.com/VIGNESYOZY/public_vitejs_staticsite_brainwave.git

  # Phase: Install dependencies
  - name: 'node:18.20.4'  # Use Node.js 18.20.4 image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        cd public_vitejs_staticsite_brainwave  # Change to the cloned repo directory
        npm install --force

  # Phase: Pre-build
  - name: 'node:18.20.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building project..."
        cd public_vitejs_staticsite_brainwave  # Change to the cloned repo directory
        npm run build --verbose

  # Phase: Log Node.js version
  - name: 'node:18.20.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Node.js version:"
        node -v  # Log the Node.js version

  # Phase: Create tar.gz archive of build files
  - name: 'node:18.20.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating tar.gz archive of build files..."
        if [ -d public_vitejs_staticsite_brainwave/dist ]; then  # Check if the build directory exists
          cd public_vitejs_staticsite_brainwave/dist  # Change to the build directory
          tar -czvf ../artiiiff.tar.gz *  # Create the archive
          echo "Tar file created at: $(pwd)/../artiiiff.tar.gz"
        else
          echo "Error: Build directory does not exist."
          exit 1  # Exit with an error if the directory doesn't exist
        fi

  # Phase: Upload to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploading tar.gz archive to Google Cloud Storage..."
        gsutil cp public_vitejs_staticsite_brainwave/artiiiff.tar.gz gs://devozy_test/devozy_test/1.0.0/artiiiff.tar.gz  # Correct path to tar.gz
        echo "Uploaded tar.gz archive to Google Cloud Storage..."
